trigger: none

pool:
  name: Default  # Replace 'Default' with your self-hosted agent pool name

stages:
- stage: Build  # First stage (has no dependencies)
  jobs:
  - job: Job1
    steps:
    - script: echo "Running Job 1 on Self-Hosted Agent"
