# Starter Pipeline to Build and Deploy to Azure App Service
trigger:
  - main  # Runs the pipeline on every push to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Uses a Microsoft-hosted agent

steps:
  - task: UseDotNet@2  # Install .NET SDK (if needed)
    inputs:
      packageType: 'sdk'
      version: '7.x'  # Change this based on your .NET version
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      echo "Building the application..."
      dotnet build --configuration Release
    displayName: 'Build the App'

  - script: |
      echo "Publishing the application..."
      dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
    displayName: 'Publish App'

  - task: PublishBuildArtifacts@1  # Save the build artifacts
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: drop

  - task: AzureWebApp@1  # Deploy to Azure App Service
    inputs:
      azureSubscription: '<Your-Azure-Service-Connection>'
      appName: '<Your-App-Service-Name>'
      package: $(Build.ArtifactStagingDirectory)
      appType: 'webApp'
